sudo: false
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
services: mongodb  
cache:  
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run lint
  - npm test
  
notifications:
  email: false
after_successs:
  # npm run deploy 
env:
- NODE_ENV=DEVELOPEMENT
