sudo: false
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
services: mongodb  

before_install:
  - npx envinfo --preset jest
  
install:
  - npm install
  
script:
  - npm test
  
notifications:
  email:
    recipients:
      - geniounico@hotmail.com
    on_success: never # default: change
    on_failure: always
    

after_failure:

env:
- NODE_ENV=DEVELOPEMENT
